spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/hc-groovebom-test
        username: postgres
        password: root
        driver-class-name: org.postgresql.Driver
    jpa:
        generate-ddl: true
        show-sql: false
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect




        
